### ISSUE TITLE
Change the parent pom to point to the Ballerina parent pom

### ISSUE THREAD

**Issue by MaryamZi** [wso2/ballerina-message-broker#342]
**Description:**
The current parent pom is the C5 pom, and this needs to be changed to the Ballerina parent pom.

Currently there are a couple of issues including MSF4J using v6.0.64 of transport-http (for org.wso2.transport.http.netty) while in Ballerina v6.0.102 is used.

**Comment by Asitha** [comment]
Decided to create our own parent pom rather than using the Ballerina lang parent pom. Issue is kept open since still we need to change the root pom.
