### ISSUE TITLE
Separation of broker runtime data from BROKER_HOME directory

### ISSUE THREAD

**Issue by Asitha** [wso2/ballerina-message-broker#408]
**Description:**

1. Separating broker runtime (instance) data from the BROKER_HOME enables the user to easily migrate from one broker version to another (given that there are no breaking changes in the code) by simply replacing the BROKER_HOME directory with the newest version.
1. Users can run several broker instances with different configuration by having multiple broker runtime instances. All the **configuration files and the data directories will be in the runtime directory**.

#### Suggestions:
We can give a method to create a runtime instance of the broker by giving helper functions in broker. 
```cmd
$ ./broker.sh create MyBrokerInstance -d /var/lib
```
This is something similar to apache artemis implementation [1]

[1] https://activemq.apache.org/artemis/docs/1.0.0/running-server.html

Resolves #489

**Comment by a5anka** [comment]
A user should also be able to provide the broker.yaml using a command line argument when the broker is started.

```
broker.sh --config <path/to.config>
```

The user only needs to specify the configs he want to override, in the pointed configuration file.
