### ISSUE TITLE
[CLI] Error message provided when executing the CLI client without running broker can be improved

### ISSUE THREAD

**Issue by hasithajayasundara** [wso2/ballerina-message-broker#444]
**Description:**
Broker need to be started before working with the commands in CLI client.Currently we get following error message when CLI commands are executed without starting the broker. 
```terminal
error calling broker https service
Connection refused (Connection refused)
```
which is somewhat counter intuitive.This can be improved.

**Affected Product Version:**
<b> 0.970.0</b>

**Steps to reproduce:**
Execute CLI commands without starting the broker.

**Comment by Asitha** [comment]
We can provide a hint as well similar to
`error calling broker https service. Please check whether the broker is running or the connectivity to the broker is not blocked through a firewall`
