### ISSUE TITLE
Create proper documentation for message-broker REST api

### ISSUE THREAD

**Issue by hasithajayasundara** [wso2/ballerina-message-broker#484]
**Description:**
Currently there is no any documentation for ballerina-message-broker REST api. We need to add a proper documentation for this.

**Comment by Asitha** [comment]
Currently, we have the [developer documentation](https://github.com/ballerina-platform/ballerina-message-broker/blob/master/docs/dev/creating-a-new-rest-module.md) on how to create REST API's but we don't have any user documentation. A better option would be to come up with a method to host the swagger files [1] within the repository itself.

[1] https://github.com/ballerina-platform/ballerina-message-broker/blob/master/modules/broker-core/src/main/resources/swagger.yaml ,
[2] https://github.com/ballerina-platform/ballerina-message-broker/blob/master/modules/broker-amqp/src/main/resources/swagger.yaml

**Comment by rjseymour66** [comment]
Hi All,

I am a professional technical writer and would like to help you document your REST APIs.  Please let me know if this is still a priority for you and I will jump in!

**Comment by Asitha** [comment]
Hi @rjseymour66, 

Glad you wanted to help us out with the REST API documentation. Yes, this is still a priority and we would very much like you to help us out in this!
